name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: write
  
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y ninja-build git meson sassc libvala-dev gobject-introspection libgtk-4-dev cmake valac gettext
  
    - name: Build package
      run: make

    - name: List artifacts
      run: ls -Rl releases target

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "releases/*.t?gz"
