name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: write
  
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y ninja-build git meson sassc libvala-dev gobject-introspection libgtk-4-dev cmake valac gettext
  
    - name: Build package
      run: make

    - name: List artifacts
      run: ls -Rl releases target

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tarball
          path: releases/*.gz
          
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "releases/*.t?gz"
        commit: ${{ needs.setup_release.outputs.release_commit }}
        prerelease: true
